swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: mockbin.org
basePath: /request
schemes:
  - https

paths:
  /:
    get:
      summary: Returns a list.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
