swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost:3000
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      Authentication tupes for bearer header

paths:
  /gets-mahasiswa:
    get:
      summary: Returns a list of post-mahasiswa.
      description: |
        Optional extended description in Markdown.
      tags:
        - "post-mahasiswa"
      parameters:
        - name: search
          in: query
          type: string
          description: parameter for search the post-mahasiswa
      produces:
        - application/json
      responses:
        200:
          description: OK
  /posts-mahasiswa:
    post:
      summary: Create new post-mahasiswa.
      description: Create new post-mahasiswa and return the created data
      tags:
        - "post-mahasiswa"
      security:
        - Bearer: []
      parameters:
        - name: create post
          in: body
          required: true
          description: Createpost body request
          schema:
            type: object
            properties:
              nama:
                type: string
              nim:
                type: number
              kelas:
                type: string
              jenis_kelamin:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: OK

  /getsone-mahasiswa/{id}:
    get:
      summary: Returns one of post-mahasiswa.
      description: |
        Returns one post with it's details and authors
      tags:
        - "post-mahasiswa"
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /edit-mahasiswa/{id}:
    put:
      summary: Update one of post
      description: |
        Update one post
      tags:
        - "post-mahasiswa"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - name: Update post
          in: body
          required: true
          description: Update post body request
          schema:
            type: object
            properties:
              nama:
                type: string
              nim:
                type: number
              kelas:
                type: string
              jenis_kelamin:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: OK

  /delete-mahasiswa/{id}:
    delete:
      summary: Delete one of post-mahasiswa.
      description: |
        Delete one post with it's details authors
      tags:
        - "post-mahasiswa"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /gets-matkul:
    get:
      summary: Returns a list of post-matkul.
      description: |
        Optional extended description in Markdown.
      tags:
        - "post-matkul"
      parameters:
        - name: search
          in: query
          type: string
          description: parameter for search the post-matkul.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /posts-matkul:
    post:
      summary: Create new post-matkul.
      description: Create new post-matkul and return the created data.
      tags:
        - "post-matkul"
      security:
        - Bearer: []
      parameters:
        - name: create post
          in: body
          required: true
          description: Createpost body request
          schema:
            type: object
            properties:
              kode:
                type: string
              nama:
                type: string
              sks:
                type: number
              kelas:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: OK

  /getsone-matkul/{id}:
    get:
      summary: Returns one of getone-matkul.
      description: |
        Returns one post with it's details and authors
      tags:
        - "post-matkul"
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /edit-matkul/{id}:
    put:
      summary: Update one of post edit-matkul
      description: |
        Update one post
      tags:
        - "post-matkul"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - name: Update post
          in: body
          required: true
          description: Update post body request
          schema:
            type: object
            properties:
              kode:
                type: string
              nama:
                type: string
              sks:
                type: number
              kelas:
                type: string
      produces:
        - application/json
      responses:
        200:
          description: OK

  /delete-matkul/{id}:
    delete:
      summary: Delete one of post-matkul.
      description: |
        Delete one post with it's details authors
      tags:
        - "post-matkul"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK
